# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageRepo : firstgame
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'firstgame'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/firstGame/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/k8s'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName : Deploy to Dev
  dependsOn: Build
  variables:
    kds: k8s-dkr-secret 
  jobs:
  - job: Deploy
    displayName: Deploy to aks
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifacts'
    - task: KubernetesManifest@1
      inputs:
        action: 'createSecret'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'sac-firstgame'
        namespace: 'firstgame'
        secretType: 'dockerRegistry'
        secretName: '$(kds)'
        dockerRegistryEndpoint: 'firstgame'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'sac-firstgame'
        namespace: 'firstgame'
        manifests: 
          $(Pipeline.Workspace)/manifacts/service.yaml
          $(Pipeline.Workspace)/manifacts/deployment.yaml