apiVersion: v1
kind: Service
metadata:
  name: front-firstgame
spec:
  type: NodePort
  selector:
    app: front-firstgame
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 80
      nodePort: 30901
